language: rust
rust:
- stable
os:
- linux
- windows
after_success:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo install cargo-aur; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo install cargo-deb; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo aur; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo deb; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell Install-WindowsFeature Net-Framework-Core; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install wixtoolset; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then cargo install cargo-wix; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then cargo wix; fi
deploy:
  provider: releases
  api_key:
    secure: K5NymtMCqH5kRknIwr75c0UGRdfhF/dInaYUNnFm68jLLhjGL1VErl3hmaUK/Z+YE4hgzLV4iNs/vcUg9tS+Nce85zoyc/tR55pGoREZyI39ykIUvsNs4mz22kOFETKcZ5AzPgEmUWlt1MtSbALryg5B0SfiV7d3Y8Gw+gOwgCnovL9R6OV59fJyqBNhMZSAI6ZqxD6zyAoLzYRDmlGZLFDSpwjD9tb8l3U01kgRHbXOceEXvlxUq2Ngf08C/YHEpRMunonWztnKqURqhbFO8xamcDYXKQ5DOeQJ8eFO+m7t8BrNCouypLhxFep4kIbnTx1+eUWuZVIm3rxNo5ZBFXg2zcqCMP19+yZ2Qp4aZOJs23O5PZXRvDQTXhwm8YcSanV5SdcIAhfV213emI08yFtmdn8NXlRHbjf7MRtfFSQzQmviOZ5y9ykaTEHb3vDR2eLVOiBigz6/C/Y5pqaxNvFJ4ZlH0zbiCB/fLR8L3CANT7ljJcVhNtoFPDtXIxqVbzCcerYe7gbQXBa16wRau1nAN9AkXmBmoitcZDoW7V5vQ+XuMjX2coVg9zZAn770AWEKYozAeLg1iOtUHL4asTmFwXaxn3kKYPnIi4uTnq8SLwTS4GcenDrL7HNqHHSFItAIP+T5hpGJv/BNmA9ttFaW8J5GFMeGo5tsrLBJ3TI=
  file:
    - "target/debian/gqg_*_amd64.deb"
    - "gqg-*-x86_64.tar.gz"
    - "target/wix/gqg-*-x86_64.msi"
  file_glob: true
  skip_cleanup: true
  on:
    os: linux
